apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Temporal Dissonance Bridge
  namespace: default
  labels:
    app: Temporal Dissonance Bridge
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Temporal Dissonance Bridge
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
