"""Tests for the agent-reports-phase-2 recovery.

Per the user's directive, 133 plain (non-Obsidian)
agent reports were ported from the vault's
Project-AI/ root to
``docs/vault-recovery/agent-reports-phase-2/``.

The 118 Obsidian-specific files were dropped.
This test verifies the cleanup is intact.
"""

from __future__ import annotations

from pathlib import Path

RECOVERY_DIR = (
    Path(__file__).resolve().parents[2] / "docs" / "vault-recovery" / "agent-reports-phase-2"
)


def test_recovery_dir_exists() -> None:
    """The recovery directory exists."""
    assert RECOVERY_DIR.exists()
    assert RECOVERY_DIR.is_dir()


def test_recovery_contains_133_markdown_files() -> None:
    """The recovery contains exactly 133 markdown
    files (plus 1 README.md = 134 total)."""
    md_files = [p for p in RECOVERY_DIR.glob("*.md") if p.name != "README.md"]
    assert len(md_files) == 133


def test_recovery_has_readme() -> None:
    """The recovery directory has a README.md."""
    readme = RECOVERY_DIR / "README.md"
    assert readme.exists()
    content = readme.read_text(encoding="utf-8")
    assert len(content) > 0


def test_no_obsidian_yaml_frontmatter() -> None:
    """No file in the recovery has Obsidian YAML
    frontmatter (``---`` at the start, with
    ``created:``/``last_verified:``/``status:``/
    ``review_cycle:`` keys)."""
    for path in RECOVERY_DIR.glob("*.md"):
        if path.name == "README.md":
            continue
        content = path.read_text(encoding="utf-8")
        if not content.startswith("---"):
            continue
        # Read first 50 lines, look for closing --- and Obsidian keys
        lines = content.split("\n")
        for i in range(1, min(50, len(lines))):
            if lines[i].strip() == "---":
                head = "\n".join(lines[:i])
                for key in ("created:", "last_verified:", "review_cycle:"):
                    assert key not in head, (
                        f"{path.name} has Obsidian key '{key}'; "
                        "should be dropped per user directive"
                    )
                break


def test_no_obsidian_wikilinks() -> None:
    """No file in the recovery has Obsidian
    wikilinks (``[[...]]``) in the first 500 chars
    (Obsidian vault cross-references)."""
    for path in RECOVERY_DIR.glob("*.md"):
        if path.name == "README.md":
            continue
        head = path.read_text(encoding="utf-8")[:500]
        # Avoid false positives in code blocks
        if "[[" in head and "]]" in head:
            # Check it's not in a code block
            # Simple heuristic: if the line starts with `, ```, or #
            for line in head.split("\n"):
                if "[[" in line and "]]" in line:
                    stripped = line.lstrip()
                    if not stripped.startswith(("`", "#", "    ", "\t")):
                        msg = f"{path.name} has Obsidian wikilink in: {line!r}"
                        raise AssertionError(msg)


def test_no_zoottelkeeper_metadata() -> None:
    """No file has Zoottelkeeper autogenerated
    vault index metadata."""
    for path in RECOVERY_DIR.glob("*.md"):
        if path.name == "README.md":
            continue
        content = path.read_text(encoding="utf-8")[:300]
        assert "Zoottelkeeper" not in content, (
            f"{path.name} has Zoottelkeeper metadata; should be dropped per user directive"
        )


def test_files_are_project_content() -> None:
    """Sample 10 files; each should be project
    audit / mission / validation content (has
    Markdown structure, reasonable length,
    references Project-AI systems)."""
    md_files = sorted(p for p in RECOVERY_DIR.glob("*.md") if p.name != "README.md")
    sample = md_files[:: len(md_files) // 10][:10]
    for path in sample:
        content = path.read_text(encoding="utf-8")
        # Reasonable length (smallest observed: 1KB)
        assert len(content) > 500, f"{path.name} is suspiciously short"
        # Has at least one Markdown header
        assert "\n##" in content or "\n###" in content, (
            f"{path.name} has no Markdown headers; doesn't look like a project document"
        )


def test_no_obsidian_vault_named_files() -> None:
    """No file in the recovery has an Obsidian-vault
    name (e.g., ``OBSIDIAN_VAULT_*``,
    ``TEMPLATER_SETUP_GUIDE*``,
    ``vault-troubleshoot*``)."""
    obsidian_name_substrings = (
        "obsidian_vault",
        "templater_setup",
        "vault-troubleshoot",
        "sovereign-vault",
        "zoottelkeeper",
        "vault_structure",
    )
    for path in RECOVERY_DIR.glob("*.md"):
        if path.name == "README.md":
            continue
        name_lower = path.name.lower()
        for sub in obsidian_name_substrings:
            assert sub not in name_lower, f"{path.name} has Obsidian-vault name fragment '{sub}'"
