apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: Paradox Resolution Service
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: Paradox Resolution Service
