apiVersion: v1
kind: Service
metadata:
  name: Entropy Injection
  namespace: default
  labels:
    app: Entropy Injection
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: Entropy Injection
  sessionAffinity: None
