apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Entropy Injection
  namespace: default
  labels:
    app: Entropy Injection
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Entropy Injection
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
