name: 'Setup Python Environment'
description: 'Unified Python environment setup with caching and dependency installation'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  install-dev-deps:
    description: 'Install development dependencies'
    required: false
    default: 'true'
  install-security-tools:
    description: 'Install security scanning tools'
    required: false
    default: 'false'
  install-test-tools:
    description: 'Install testing tools'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
          requirements.lock
    
    - name: Upgrade pip
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
    
    - name: Install core dependencies
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        elif [ -f pyproject.toml ]; then
          pip install -e .
        fi
    
    - name: Install development dependencies
      if: inputs.install-dev-deps == 'true'
      shell: bash
      run: |
        pip install ruff black isort mypy autopep8 flake8
        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi
    
    - name: Install security tools
      if: inputs.install-security-tools == 'true'
      shell: bash
      run: |
        pip install bandit[sarif] detect-secrets truffleHog3 safety pip-audit
    
    - name: Install testing tools
      if: inputs.install-test-tools == 'true'
      shell: bash
      run: |
        pip install pytest pytest-cov pytest-xdist pytest-asyncio pytest-mock coverage
