apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Zero-downtime deploys
  namespace: default
  labels:
    app: Zero-downtime deploys
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Zero-downtime deploys
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
