apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Linguistics & Etymology Service
  namespace: default
  labels:
    app: Linguistics & Etymology Service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Linguistics & Etymology Service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
