"""Deterministic, read-only repository source indexing.

The scanner is deliberately conservative: it reads only UTF-8 text files that
look like source or documentation, never executes repository code, never follows
symlinks, and never writes during discovery or search.  Persistence is an
explicit offline operation through :meth:`RepositoryIndex.save`.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from collections.abc import Iterable, Mapping
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import TypedDict

SCHEMA_VERSION = "repository-index-v1"
DEFAULT_CHUNK_LINES = 80
DEFAULT_OVERLAP_LINES = 10
DEFAULT_MAX_FILE_BYTES = 1_000_000

# These names are intentionally broader than the current repository layout.  A
# repository index should not accidentally ingest package managers, generated
# output, build products, local caches, or virtual environments when reused in
# another checkout.
EXCLUDED_DIRECTORIES = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        ".venv",
        "venv",
        "env",
        "ENV",
        "node_modules",
        ".pnpm-store",
        "vendor",
        "vendors",
        "third_party",
        "third-party",
        "dependencies",
        "dependency",
        "deps",
        "external",
        "site-packages",
        "bower_components",
        "pods",
        "generated",
        "__generated__",
        "build",
        "builds",
        "dist",
        "out",
        "target",
        "coverage",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        # Common generated reports and build outputs.
        "output",
        "outputs",
        "artifacts",
        "reports",
        ".claude",
        ".ruff_cache",
        ".tox",
        ".cache",
        ".parcel-cache",
        ".next",
        ".turbo",
        ".gradle",
        "cache",
        "caches",
        "tmp",
        ".tmp",
        "temp",
        "__snapshots__",
        # The repository's derived data and index artifacts live here.  Keeping
        # the whole directory out also prevents self-indexing on refresh.
        "data",
    }
)
SECRET_NAMES = frozenset(
    {
        ".env",
        ".env.local",
        ".env.production",
        ".env.development",
        ".npmrc",
        "id_rsa",
        "id_dsa",
        "id_ecdsa",
        "id_ed25519",
        "known_hosts",
    }
)
SECRET_EXTENSIONS = frozenset({".pem", ".key", ".p12", ".pfx", ".jks", ".keystore"})
SECRET_WORDS = frozenset(
    {"secret", "secrets", "credential", "credentials", "password", "passwd", "token", "private"}
)
GENERATED_WORDS = frozenset({"generated", "autogenerated", "autogen", "designer"})
SUPPORTED_NAMES = frozenset({"dockerfile", "makefile", "readme", "license", "changelog"})
SUPPORTED_EXTENSIONS = frozenset(
    {
        ".py",
        ".pyi",
        ".js",
        ".jsx",
        ".ts",
        ".tsx",
        ".mjs",
        ".cjs",
        ".java",
        ".kt",
        ".kts",
        ".go",
        ".rs",
        ".c",
        ".h",
        ".cc",
        ".cpp",
        ".hpp",
        ".cs",
        ".swift",
        ".dart",
        ".md",
        ".markdown",
        ".rst",
        ".txt",
        ".yaml",
        ".yml",
        ".json",
        ".toml",
        ".ini",
        ".cfg",
        ".conf",
        ".xml",
        ".gradle",
        ".sql",
        ".sh",
        ".bash",
        ".bat",
        ".cmd",
        ".ps1",
        ".html",
        ".htm",
        ".css",
        ".scss",
        ".proto",
        ".properties",
        ".lock",
    }
)
LANGUAGE_BY_EXTENSION = {
    ".py": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".go": "go",
    ".rs": "rust",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".swift": "swift",
    ".dart": "dart",
    ".md": "markdown",
    ".markdown": "markdown",
    ".rst": "rst",
    ".txt": "text",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".json": "json",
    ".toml": "toml",
    ".ini": "ini",
    ".cfg": "config",
    ".conf": "config",
    ".xml": "xml",
    ".gradle": "gradle",
    ".sql": "sql",
    ".sh": "shell",
    ".bash": "shell",
    ".bat": "batch",
    ".cmd": "batch",
    ".ps1": "powershell",
    ".html": "html",
    ".htm": "html",
    ".css": "css",
    ".scss": "scss",
    ".proto": "protobuf",
    ".properties": "properties",
    ".lock": "text",
}
_TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_./\\:-]*")
_WORD_RE = re.compile(r"[a-z0-9]+")


class RepositoryIndexError(RuntimeError):
    """Base error for invalid or unavailable repository indexes."""


class IndexUnavailable(RepositoryIndexError):
    """Raised when an index is missing, corrupt, incompatible, or stale."""


@dataclass(frozen=True)
class RepositoryChunk:
    chunk_id: str
    path: str
    language: str
    start_line: int
    end_line: int
    sha256: str
    excerpt: str

    def as_dict(self) -> dict[str, object]:
        return asdict(self)


class RepositoryStatusDict(TypedDict):
    schema_version: str
    state: str
    root: str
    root_fingerprint: str | None
    indexed_files: int
    indexed_chunks: int
    excluded_files: int
    exclusions: dict[str, int]
    index_path: str
    stale: bool
    reason: str | None


@dataclass(frozen=True)
class RepositoryStatus:
    schema_version: str
    state: str
    root: str
    root_fingerprint: str | None
    indexed_files: int
    indexed_chunks: int
    excluded_files: int
    exclusions: Mapping[str, int]
    index_path: str
    stale: bool
    reason: str | None = None

    def as_dict(self) -> RepositoryStatusDict:
        return {
            "schema_version": self.schema_version,
            "state": self.state,
            "root": self.root,
            "root_fingerprint": self.root_fingerprint,
            "indexed_files": self.indexed_files,
            "indexed_chunks": self.indexed_chunks,
            "excluded_files": self.excluded_files,
            "exclusions": dict(self.exclusions),
            "index_path": self.index_path,
            "stale": self.stale,
            "reason": self.reason,
        }


def _canonical_root(root: Path) -> Path:
    return root.expanduser().resolve(strict=True)


def _root_string(root: Path) -> str:
    return root.as_posix()


def _language(path: Path) -> str:
    lower = path.name.lower()
    if lower in SUPPORTED_NAMES:
        return "text"
    return LANGUAGE_BY_EXTENSION.get(path.suffix.lower(), "text")


def _name_words(name: str) -> set[str]:
    return set(_WORD_RE.findall(name.lower()))


def _is_secret(path: Path) -> bool:
    lower = path.name.lower()
    if lower in SECRET_NAMES or path.suffix.lower() in SECRET_EXTENSIONS:
        return True
    return bool(_name_words(path.stem) & SECRET_WORDS)


def _is_generated(path: Path) -> bool:
    lower = path.name.lower()
    if any(
        marker in lower
        for marker in (".generated.", ".autogenerated.", ".designer.", ".min.", ".bundle.")
    ):
        return True
    return bool(_name_words(path.stem) & GENERATED_WORDS) or lower.endswith(".map")


def _candidate(path: Path, root: Path) -> tuple[bool, str]:
    try:
        relative = path.relative_to(root)
    except ValueError:
        return False, "outside-root"
    if path.is_symlink():
        return False, "symlink"
    if any(
        part.lower() in {item.lower() for item in EXCLUDED_DIRECTORIES}
        for part in relative.parts[:-1]
    ):
        return False, "excluded-directory"
    if _is_secret(path):
        return False, "secret-like-name"
    if _is_generated(path):
        return False, "generated-file"
    if path.name.lower() not in SUPPORTED_NAMES and path.suffix.lower() not in SUPPORTED_EXTENSIONS:
        return False, "unsupported-extension"
    return True, ""


def _read_text(path: Path) -> tuple[str | None, str]:
    try:
        if path.stat().st_size > DEFAULT_MAX_FILE_BYTES:
            return None, "file-too-large"
        raw = path.read_bytes()
    except (OSError, ValueError):
        return None, "unreadable"
    if b"\x00" in raw:
        return None, "binary-content"
    try:
        return raw.decode("utf-8"), ""
    except UnicodeDecodeError:
        return None, "non-utf8-content"


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _fingerprint(root: Path, files: Iterable[tuple[str, str]]) -> str:
    digest = hashlib.sha256()
    digest.update(SCHEMA_VERSION.encode("utf-8"))
    digest.update(b"\n")
    for path, file_hash in files:
        digest.update(path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(file_hash.encode("ascii"))
        digest.update(b"\n")
    return digest.hexdigest()


def _chunks(
    path: str, language: str, sha256: str, text: str, chunk_lines: int, overlap: int
) -> list[RepositoryChunk]:
    lines = text.splitlines()
    if not lines:
        return []
    result: list[RepositoryChunk] = []
    step = max(1, chunk_lines - overlap)
    for start in range(0, len(lines), step):
        end = min(len(lines), start + chunk_lines)
        excerpt = "\n".join(lines[start:end]).strip()
        if excerpt:
            identity = f"{path}:{start + 1}:{end}:{sha256}:{excerpt}"
            result.append(
                RepositoryChunk(
                    chunk_id=hashlib.sha256(identity.encode("utf-8")).hexdigest(),
                    path=path,
                    language=language,
                    start_line=start + 1,
                    end_line=end,
                    sha256=sha256,
                    excerpt=excerpt,
                )
            )
        if end == len(lines):
            break
    return result


def _under(path: Path, roots: tuple[Path, ...]) -> bool:
    return any(path == excluded or excluded in path.parents for excluded in roots)


def discover_repository(
    root: Path, *, excluded_paths: Iterable[Path] = ()
) -> tuple[list[tuple[Path, str, str, str]], dict[str, int]]:
    """Discover eligible files without changing the filesystem.

    ``excluded_paths`` protects a caller-selected artifact directory even when
    it is nested inside the repository.  The default also excludes ``data``
    through :data:`EXCLUDED_DIRECTORIES`, preventing self-indexing of the
    repository's derived artifacts.
    """
    root = _canonical_root(root)
    excluded = tuple(Path(item).expanduser().resolve(strict=False) for item in excluded_paths)
    excluded_directory_names = {item.lower() for item in EXCLUDED_DIRECTORIES}
    found: list[tuple[Path, str, str, str]] = []
    exclusions: dict[str, int] = {}
    for current, dirs, names in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        kept_dirs: list[str] = []
        for directory in sorted(dirs):
            directory_path = current_path / directory
            if _under(directory_path, excluded):
                exclusions["excluded-artifact"] = exclusions.get("excluded-artifact", 0) + 1
            elif directory.lower() in excluded_directory_names:
                # Keep a directory-name exclusion only when it is an ancestor
                # of an explicitly protected artifact, so the walk can reach
                # and count that artifact without indexing its contents.
                has_explicit_descendant = any(
                    directory_path in excluded_root.parents for excluded_root in excluded
                )
                if has_explicit_descendant:
                    kept_dirs.append(directory)
                else:
                    exclusions["excluded-directory"] = exclusions.get("excluded-directory", 0) + 1
            else:
                kept_dirs.append(directory)
        dirs[:] = kept_dirs
        for name in sorted(names):
            path = current_path / name
            if _under(path, excluded):
                exclusions["excluded-artifact"] = exclusions.get("excluded-artifact", 0) + 1
                continue
            ok, reason = _candidate(path, root)
            if not ok:
                exclusions[reason] = exclusions.get(reason, 0) + 1
                continue
            text, reason = _read_text(path)
            if text is None:
                exclusions[reason] = exclusions.get(reason, 0) + 1
                continue
            relative = path.relative_to(root).as_posix()
            digest = _sha256(text.encode("utf-8"))
            found.append((path, relative, _language(path), digest))
    return found, dict(sorted(exclusions.items()))


class RepositoryIndex:
    """Immutable in-memory repository index with deterministic lexical retrieval."""

    def __init__(self, root: Path, chunks: Iterable[RepositoryChunk], status: RepositoryStatus):
        self.root = _canonical_root(root)
        self.chunks = tuple(chunks)
        self.status = status

    @classmethod
    def build(
        cls,
        root: Path,
        *,
        chunk_lines: int = DEFAULT_CHUNK_LINES,
        overlap: int = DEFAULT_OVERLAP_LINES,
        excluded_paths: Iterable[Path] = (),
    ) -> RepositoryIndex:
        if chunk_lines <= 0 or overlap < 0 or overlap >= chunk_lines:
            raise ValueError(
                "chunk_lines must be positive and overlap must be smaller than chunk_lines"
            )
        root = _canonical_root(root)
        discovered, exclusions = discover_repository(root, excluded_paths=excluded_paths)
        chunks: list[RepositoryChunk] = []
        file_hashes: list[tuple[str, str]] = []
        for path, relative, language, digest in discovered:
            text, reason = _read_text(path)
            if text is None:
                exclusions[reason] = exclusions.get(reason, 0) + 1
                continue
            file_hashes.append((relative, digest))
            chunks.extend(_chunks(relative, language, digest, text, chunk_lines, overlap))
        chunks.sort(key=lambda item: (item.path, item.start_line, item.end_line, item.chunk_id))
        fingerprint = _fingerprint(root, sorted(file_hashes))
        status = RepositoryStatus(
            schema_version=SCHEMA_VERSION,
            state="ready" if chunks else "empty",
            root=_root_string(root),
            root_fingerprint=fingerprint,
            indexed_files=len(file_hashes),
            indexed_chunks=len(chunks),
            excluded_files=sum(exclusions.values()),
            exclusions=dict(sorted(exclusions.items())),
            index_path="",
            stale=False,
        )
        return cls(root, chunks, status)

    def search(self, query: str, limit: int = 10) -> tuple[tuple[RepositoryChunk, float], ...]:
        if not isinstance(query, str) or not query.strip():
            raise ValueError("query must not be empty")
        if not isinstance(limit, int) or isinstance(limit, bool) or not 1 <= limit <= 50:
            raise ValueError("limit must be between 1 and 50")
        query_clean = query.strip().lower()
        query_tokens = [token.lower() for token in _TOKEN_RE.findall(query_clean)]
        phrase = " ".join(query_tokens)
        scored: list[tuple[RepositoryChunk, float]] = []
        for chunk in self.chunks:
            path = chunk.path.lower()
            text = chunk.excerpt.lower()
            token_hits = sum(text.count(token) for token in query_tokens if token)
            path_hits = sum(path.count(token) for token in query_tokens if token)
            phrase_hit = 1.0 if phrase and (phrase in text or phrase in path) else 0.0
            exact_path = 1.0 if query_clean.replace("\\", "/") in path else 0.0
            if token_hits or path_hits or phrase_hit or exact_path:
                score = (
                    float(token_hits) + (2.0 * path_hits) + (8.0 * phrase_hit) + (12.0 * exact_path)
                )
                scored.append((chunk, score))
        scored.sort(key=lambda pair: (-pair[1], pair[0].path, pair[0].start_line, pair[0].chunk_id))
        return tuple(scored[:limit])

    def save(self, directory: Path) -> Path:
        directory = Path(directory).expanduser().resolve()
        directory.mkdir(parents=True, exist_ok=True)
        status = asdict(self.status)
        status["index_path"] = directory.as_posix()
        status["exclusions"] = dict(sorted(self.status.exclusions.items()))
        manifest = {
            "schema_version": SCHEMA_VERSION,
            "root": self.status.root,
            "root_fingerprint": self.status.root_fingerprint,
            "indexed_files": self.status.indexed_files,
            "indexed_chunks": self.status.indexed_chunks,
            "excluded_files": self.status.excluded_files,
            "exclusions": dict(sorted(self.status.exclusions.items())),
            "build_timestamp_utc": None,
            "deterministic": True,
        }
        records = [chunk.as_dict() for chunk in self.chunks]
        (directory / "manifest.json").write_text(
            json.dumps(manifest, sort_keys=True, indent=2) + "\n", encoding="utf-8"
        )
        (directory / "status.json").write_text(
            json.dumps(status, sort_keys=True, indent=2) + "\n", encoding="utf-8"
        )
        (directory / "records.json").write_text(
            json.dumps(records, sort_keys=True, indent=2) + "\n", encoding="utf-8"
        )
        return directory

    @classmethod
    def load(
        cls,
        directory: Path,
        *,
        root: Path | None = None,
        allow_stale: bool = False,
    ) -> RepositoryIndex:
        directory = Path(directory).expanduser().resolve()
        try:
            manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
            records_data = json.loads((directory / "records.json").read_text(encoding="utf-8"))
            if manifest.get("schema_version") != SCHEMA_VERSION or not isinstance(
                records_data, list
            ):
                raise IndexUnavailable("repository index schema is incompatible")
            actual_root = _canonical_root(root or Path(manifest["root"]))
            current = cls.build(actual_root, excluded_paths=(directory,))
            expected = manifest.get("root_fingerprint")
            stale = expected != current.status.root_fingerprint
            if stale and not allow_stale:
                raise IndexUnavailable("repository index is stale; rebuild it offline")
            chunks = tuple(RepositoryChunk(**item) for item in records_data)
        except IndexUnavailable:
            raise
        except (OSError, ValueError, TypeError, KeyError) as exc:
            raise IndexUnavailable("repository index is missing or corrupt") from exc
        status = RepositoryStatus(
            schema_version=SCHEMA_VERSION,
            state="stale" if stale else "ready",
            root=_root_string(actual_root),
            root_fingerprint=expected,
            indexed_files=int(manifest.get("indexed_files", 0)),
            indexed_chunks=len(chunks),
            excluded_files=int(manifest.get("excluded_files", 0)),
            exclusions=manifest.get("exclusions", {}),
            index_path=directory.as_posix(),
            stale=stale,
            reason="source fingerprint differs" if stale else None,
        )
        return cls(actual_root, chunks, status)

    @classmethod
    def status_for(cls, directory: Path, *, root: Path) -> RepositoryStatus:
        directory = Path(directory).expanduser().resolve()
        manifest_path = directory / "manifest.json"
        records_path = directory / "records.json"
        try:
            canonical_root = _canonical_root(root)
        except (OSError, ValueError) as exc:
            return RepositoryStatus(
                SCHEMA_VERSION,
                "corrupt",
                str(root),
                None,
                0,
                0,
                0,
                {},
                directory.as_posix(),
                True,
                str(exc),
            )
        if not manifest_path.exists() or not records_path.exists():
            return RepositoryStatus(
                SCHEMA_VERSION,
                "missing",
                _root_string(canonical_root),
                None,
                0,
                0,
                0,
                {},
                directory.as_posix(),
                True,
                "index artifacts are missing",
            )
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            current = cls.build(canonical_root, excluded_paths=(directory,))
            if manifest.get("schema_version") != SCHEMA_VERSION:
                raise ValueError("repository index schema is incompatible")
        except (OSError, ValueError, KeyError, TypeError, RepositoryIndexError) as exc:
            return RepositoryStatus(
                SCHEMA_VERSION,
                "corrupt",
                _root_string(canonical_root),
                None,
                0,
                0,
                0,
                {},
                directory.as_posix(),
                True,
                str(exc),
            )
        stale = manifest.get("root_fingerprint") != current.status.root_fingerprint
        return RepositoryStatus(
            SCHEMA_VERSION,
            "stale" if stale else "ready",
            current.status.root,
            manifest.get("root_fingerprint"),
            int(manifest.get("indexed_files", 0)),
            int(manifest.get("indexed_chunks", 0)),
            int(manifest.get("excluded_files", 0)),
            manifest.get("exclusions", {}),
            directory.as_posix(),
            stale,
            "source fingerprint differs" if stale else None,
        )


def build_repository_index(root: Path, output: Path) -> RepositoryStatus:
    """Build and persist an index; writes occur only inside ``output``."""
    output = Path(output).expanduser().resolve()
    index = RepositoryIndex.build(root, excluded_paths=(output,))
    index.save(output)
    return RepositoryIndex.status_for(output, root=root)
