name: 'Setup Node.js Environment'
description: 'Unified Node.js environment setup with caching'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  install-deps:
    description: 'Install dependencies from package.json'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          package.json
    
    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        elif [ -f package.json ]; then
          npm install
        else
          echo "No package.json found, skipping installation"
        fi
