apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Built-in observability
  namespace: default
  labels:
    app: Built-in observability
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Built-in observability
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
