apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Multi-cloud support
  namespace: default
  labels:
    app: Multi-cloud support
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Multi-cloud support
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
