apiVersion: v1
kind: Service
metadata:
  name: Multi-cloud support
  namespace: default
  labels:
    app: Multi-cloud support
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: Multi-cloud support
  sessionAffinity: None
