"""Filesystem + content analyzer for the Project-AI audit receipt.

Read-only. Walks the repository from ROOT, classifies files, and writes raw
per-measurement outputs plus a machine-readable fs_metrics.json into the
receipt directory. Line counts are self-computed (tokei/cloc cross-checked
separately); assertion/test-function counts are text-based with stated limits.
"""

from __future__ import annotations

import json
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(sys.argv[1]).resolve()
RECEIPT_NAME = sys.argv[2]
RAW = ROOT / RECEIPT_NAME / "raw"
RAW.mkdir(parents=True, exist_ok=True)

# Item 3 / 35 / 48 — standard exclusions (generated / cache / dependency / build).
EXCLUDE_DIRS = {
    ".git", ".venv", "venv", "node_modules", "__pycache__", ".pytest_cache",
    ".mypy_cache", ".ruff_cache", "dist", "build", "coverage", "htmlcov",
    "target", "out", ".gradle", ".idea", ".pytest_tmp", ".tox", ".cache",
    "site-packages", ".next", ".turbo", ".parcel-cache",
}
# The receipt directory itself is generated by this audit — always excluded.
EXCLUDE_TOPLEVEL = {RECEIPT_NAME}

# Repo-specific byte-preserved / reference / evidence trees (reported separately).
VENDORED_PREFIXES = (
    "packages/_staging/",
    "packages/security/reference/",
    "packages/rlp/governance_framework/",
    "docs/reference/",
    "docs/internal/frozen-history/",
)
EVIDENCE_PREFIXES = ("docs/internal/verification/",)
REPORT_PREFIXES = ("docs/operations/deployment-reports/",)
DEP_LOCKFILES = {"uv.lock", "pnpm-lock.yaml", "package-lock.json", "Cargo.lock", "poetry.lock"}

LANG_BY_EXT = {
    ".py": "Python", ".pyi": "Python", ".md": "Markdown", ".rst": "reStructuredText",
    ".yaml": "YAML", ".yml": "YAML", ".json": "JSON", ".jsonl": "JSONL",
    ".js": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript",
    ".ts": "TypeScript", ".tsx": "TSX", ".jsx": "JSX", ".rs": "Rust", ".go": "Go",
    ".java": "Java", ".kt": "Kotlin", ".kts": "Kotlin", ".c": "C", ".h": "C/C++ header",
    ".cpp": "C++", ".cc": "C++", ".cs": "C#", ".sh": "Shell", ".bash": "Shell",
    ".ps1": "PowerShell", ".psm1": "PowerShell", ".tf": "Terraform", ".hcl": "HCL",
    ".proto": "Protobuf", ".sql": "SQL", ".toml": "TOML", ".ini": "INI", ".cfg": "INI",
    ".css": "CSS", ".html": "HTML", ".htm": "HTML", ".svg": "SVG", ".txt": "Text",
    ".thirsty": "Thirsty", ".tarl": "TARL", ".tscg": "TSCG-spec", ".gradle": "Gradle",
    ".xml": "XML", ".csv": "CSV", ".bat": "Batch", ".pdf": "PDF",
}
BINARY_EXTS = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".pdf", ".zip", ".gz", ".tar", ".7z",
    ".woff", ".woff2", ".ttf", ".eot", ".jar", ".class", ".pyc", ".so", ".dll",
    ".exe", ".bin", ".wasm", ".webp", ".mp4", ".mp3", ".keystore",
}
# Item 20 explicit buckets.
BUCKET_EXTS = {
    "Python": {".py", ".pyi"}, "Markdown": {".md"}, "YAML": {".yaml", ".yml"},
    "JSON": {".json", ".jsonl"}, "JavaScript": {".js", ".mjs", ".cjs"},
    "TypeScript": {".ts"}, "TSX": {".tsx"}, "JSX": {".jsx"}, "Rust": {".rs"},
    "Go": {".go"}, "Java": {".java"}, "C": {".c", ".h"}, "C++": {".cpp", ".cc", ".hpp"},
    "C#": {".cs"}, "Shell": {".sh", ".bash"}, "PowerShell": {".ps1", ".psm1"},
    "Terraform": {".tf"}, "Protobuf": {".proto"}, "SQL": {".sql"},
    "thirsty": {".thirsty"}, "TARL": {".tarl"},
}


def rel(p: Path) -> str:
    return p.relative_to(ROOT).as_posix()


def is_excluded(relpath: str) -> bool:
    parts = relpath.split("/")
    if parts[0] in EXCLUDE_TOPLEVEL:
        return True
    return any(part in EXCLUDE_DIRS for part in parts)


def category(relpath: str, ext: str) -> str:
    name = relpath.rsplit("/", 1)[-1]
    if any(relpath.startswith(p) for p in EVIDENCE_PREFIXES):
        return "evidence"
    if any(relpath.startswith(p) for p in VENDORED_PREFIXES):
        return "vendored/reference"
    if any(relpath.startswith(p) for p in REPORT_PREFIXES):
        return "reports"
    if name in DEP_LOCKFILES:
        return "dependency"
    if "/tests/" in f"/{relpath}" or name.startswith("test_") or name.endswith("_test.py") \
            or name == "conftest.py" or ".test." in name or ".spec." in name:
        return "test"
    if relpath.startswith("helm/") or relpath.startswith("docker") or name == "Dockerfile" \
            or name.startswith("Dockerfile") or ext == ".tf" or "compose" in name \
            or relpath.startswith(".github/"):
        return "infrastructure"
    if ext in {".png", ".jpg", ".jpeg", ".gif", ".ico", ".svg", ".woff", ".woff2",
               ".ttf", ".eot", ".webp", ".mp4", ".mp3"}:
        return "asset"
    if relpath.startswith("docs/") or ext in {".md", ".rst"}:
        return "documentation"
    if ext in {".toml", ".cfg", ".ini", ".yaml", ".yml", ".json", ".editorconfig"} \
            or name in {".gitignore", ".gitattributes"}:
        return "configuration"
    if ext in {".py", ".rs", ".go", ".java", ".ts", ".tsx", ".js", ".jsx", ".c",
               ".cpp", ".cs", ".sh", ".ps1", ".sql", ".proto", ".thirsty", ".tarl"}:
        return "source"
    return "other"


# ---- pass 1: every physical file (incl .git) -------------------------------
all_count = 0
all_bytes = 0
git_count = 0
git_bytes = 0
records: list[tuple[str, int, str]] = []  # (relpath, size, ext) for non-.git

for dirpath, dirnames, filenames in os.walk(ROOT):
    dirnames.sort()
    for fn in sorted(filenames):
        fp = Path(dirpath) / fn
        try:
            size = fp.stat().st_size
        except OSError:
            size = 0
        try:
            rp = rel(fp)
        except ValueError:
            continue
        all_count += 1
        all_bytes += size
        if rp.split("/")[0] == ".git":
            git_count += 1
            git_bytes += size
            continue
        ext = fp.suffix.lower()
        records.append((rp, size, ext))

# ---- excluded vs kept ------------------------------------------------------
kept = [(rp, sz, ext) for (rp, sz, ext) in records if not is_excluded(rp)]
excluded_nongit = [(rp, sz, ext) for (rp, sz, ext) in records if is_excluded(rp)]

# ---- by top-level directory (kept set) -------------------------------------
topdir_count: dict[str, int] = defaultdict(int)
topdir_bytes: dict[str, int] = defaultdict(int)
for rp, sz, _ in kept:
    top = rp.split("/")[0] if "/" in rp else "(root file)"
    topdir_count[top] += 1
    topdir_bytes[top] += sz

# ---- by extension (kept) ---------------------------------------------------
ext_count: dict[str, int] = defaultdict(int)
ext_bytes: dict[str, int] = defaultdict(int)
for rp, sz, ext in kept:
    key = ext if ext else "(no extension)"
    ext_count[key] += 1
    ext_bytes[key] += sz

# ---- categories (kept) -----------------------------------------------------
cat_count: dict[str, int] = defaultdict(int)
cat_bytes: dict[str, int] = defaultdict(int)
for rp, sz, ext in kept:
    c = category(rp, ext)
    cat_count[c] += 1
    cat_bytes[c] += sz

# ---- item 20 buckets (kept) ------------------------------------------------
bucket_count: dict[str, int] = defaultdict(int)
for rp, sz, ext in kept:
    for bucket, exts in BUCKET_EXTS.items():
        if ext in exts:
            bucket_count[bucket] += 1
noext = sum(1 for rp, _, ext in kept if ext == "")
dockerfiles = sum(1 for rp, _, _ in kept if rp.rsplit("/", 1)[-1].startswith("Dockerfile"))
helm_files = sum(1 for rp, _, _ in kept if rp.startswith("helm/"))
k8s_like = sum(
    1 for rp, _, ext in kept
    if ext in {".yaml", ".yml"} and (rp.startswith("helm/") or "k8s" in rp or "kube" in rp)
)

# ---- line counts (kept, text files) ----------------------------------------
lang_files: dict[str, int] = defaultdict(int)
lang_total: dict[str, int] = defaultdict(int)
lang_nonblank: dict[str, int] = defaultdict(int)
for rp, sz, ext in kept:
    if ext in BINARY_EXTS or sz > 5_000_000:
        continue
    lang = LANG_BY_EXT.get(ext)
    if lang is None:
        continue
    try:
        text = (ROOT / rp).read_text(encoding="utf-8", errors="strict")
    except (OSError, UnicodeDecodeError):
        continue
    lines = text.splitlines()
    lang_files[lang] += 1
    lang_total[lang] += len(lines)
    lang_nonblank[lang] += sum(1 for ln in lines if ln.strip())

# ---- tests (item 21-23) ----------------------------------------------------
test_files = [rp for rp, _, ext in kept if category(rp, ext) == "test"]
py_test_files = [rp for rp in test_files if rp.endswith(".py")]
test_func_re = re.compile(r"^\s*(async\s+)?def\s+test\w*\s*\(", re.MULTILINE)
assert_re = re.compile(r"(^|\s)assert(\s|\()")
raises_re = re.compile(r"pytest\.raises|self\.assert\w+|expect\(")
py_test_funcs = 0
assert_stmts = 0
assert_like = 0
for rp in py_test_files:
    try:
        t = (ROOT / rp).read_text(encoding="utf-8", errors="ignore")
    except OSError:
        continue
    py_test_funcs += len(test_func_re.findall(t))
    assert_stmts += len(assert_re.findall(t))
# repo-wide assert count (all python, not just tests) for context
all_py = [rp for rp, _, ext in kept if ext == ".py"]
assert_all_py = 0
for rp in all_py:
    try:
        t = (ROOT / rp).read_text(encoding="utf-8", errors="ignore")
    except OSError:
        continue
    assert_all_py += len(assert_re.findall(t))
    assert_like += len(raises_re.findall(t))
# JS/TS test cases (it()/test())
js_test_files = [rp for rp in test_files if rp.endswith((".js", ".ts", ".tsx", ".jsx"))]
js_cases = 0
js_case_re = re.compile(r"\b(it|test)\s*\(")
for rp in js_test_files:
    try:
        t = (ROOT / rp).read_text(encoding="utf-8", errors="ignore")
    except OSError:
        continue
    js_cases += len(js_case_re.findall(t))

# ---- largest dirs / files --------------------------------------------------
dir_count: dict[str, int] = defaultdict(int)
dir_bytes: dict[str, int] = defaultdict(int)
for rp, sz, _ in kept:
    d = rp.rsplit("/", 1)[0] if "/" in rp else "(root)"
    dir_count[d] += 1
    dir_bytes[d] += sz
largest_dirs_count = sorted(dir_count.items(), key=lambda kv: -kv[1])[:100]
largest_dirs_bytes = sorted(dir_bytes.items(), key=lambda kv: -kv[1])[:100]
largest_files = sorted(kept, key=lambda r: -r[1])[:100]

# ---- prometheus (item 34) --------------------------------------------------
prom_files = []
for rp, sz, ext in kept:
    name = rp.rsplit("/", 1)[-1].lower()
    hit = "prometheus" in rp.lower() or "prometheus" in name
    content_hit = False
    if not hit and ext in {".yaml", ".yml", ".md", ".py", ".json", ".tpl"} and sz < 2_000_000:
        try:
            content_hit = "prometheus" in (ROOT / rp).read_text(
                encoding="utf-8", errors="ignore").lower()
        except OSError:
            content_hit = False
    if hit or content_hit:
        if "prometheusrule" in rp.lower():
            klass = "monitoring rule (PrometheusRule CR)"
        elif ext in {".yaml", ".yml"} and rp.startswith("helm/"):
            klass = "helm template / config"
        elif ext == ".py":
            klass = "integration code / reference"
        elif ext == ".md":
            klass = "documentation"
        else:
            klass = "config/other"
        prom_files.append((rp, "name" if hit else "content", klass))

# ---- write raw outputs -----------------------------------------------------
def w(name: str, lines: list[str]) -> None:
    (RAW / name).write_text("\n".join(lines) + "\n", encoding="utf-8")


w("02_physical_all.txt", [
    f"physical files (all, including .git): {all_count}",
    f"physical bytes (all, including .git): {all_bytes}",
    f".git files: {git_count}",
    f".git bytes: {git_bytes}",
])
w("03_physical_excluded.txt", [
    f"non-.git files: {len(records)}",
    f"excluded (cache/dep/build/generated + receipt dir): {len(excluded_nongit)}",
    f"files after standard exclusions: {len(kept)}",
    "",
    "excluded breakdown by top-level segment matched:",
])
excl_by_seg: dict[str, int] = defaultdict(int)
excl_bytes_by_seg: dict[str, int] = defaultdict(int)
for rp, sz, _ in excluded_nongit:
    seg = next((p for p in rp.split("/") if p in EXCLUDE_DIRS or p in EXCLUDE_TOPLEVEL), rp.split("/")[0])
    excl_by_seg[seg] += 1
    excl_bytes_by_seg[seg] += sz
with (RAW / "36_excluded_counts.txt").open("w", encoding="utf-8") as f:
    f.write(f"{'segment':40} {'files':>8} {'bytes':>14}\n")
    for seg, c in sorted(excl_by_seg.items(), key=lambda kv: -kv[1]):
        f.write(f"{seg:40} {c:>8} {excl_bytes_by_seg[seg]:>14}\n")

w("06_size_excl_git.txt", [
    f"total non-.git bytes: {sum(sz for _, sz, _ in records)}",
    f"kept (post-exclusion) bytes: {sum(sz for _, sz, _ in kept)}",
])

with (RAW / "04_by_topdir.txt").open("w", encoding="utf-8") as f:
    f.write(f"{'top-level':32} {'files':>8} {'bytes':>14}\n")
    for d in sorted(topdir_count, key=lambda k: -topdir_count[k]):
        f.write(f"{d:32} {topdir_count[d]:>8} {topdir_bytes[d]:>14}\n")

with (RAW / "05_by_extension.txt").open("w", encoding="utf-8") as f:
    f.write(f"{'ext':16} {'files':>8} {'bytes':>14}\n")
    for e in sorted(ext_count, key=lambda k: -ext_count[k]):
        f.write(f"{e:16} {ext_count[e]:>8} {ext_bytes[e]:>14}\n")

with (RAW / "19_by_category.txt").open("w", encoding="utf-8") as f:
    f.write("Heuristic category split of kept (post-exclusion) files.\n")
    f.write(f"{'category':22} {'files':>8} {'bytes':>14}\n")
    for c in sorted(cat_count, key=lambda k: -cat_count[k]):
        f.write(f"{c:22} {cat_count[c]:>8} {cat_bytes[c]:>14}\n")

with (RAW / "20_ext_buckets.txt").open("w", encoding="utf-8") as f:
    for b in sorted(bucket_count, key=lambda k: -bucket_count[k]):
        f.write(f"{b:16} {bucket_count[b]}\n")
    f.write(f"{'(no extension)':16} {noext}\n")
    f.write(f"{'Dockerfile*':16} {dockerfiles}\n")
    f.write(f"{'helm/* files':16} {helm_files}\n")
    f.write(f"{'k8s-like yaml':16} {k8s_like}\n")

with (RAW / "18_linecount_self.txt").open("w", encoding="utf-8") as f:
    f.write("Self-computed line counts (kept text files). total = physical lines; "
            "non-blank excludes whitespace-only lines. Comment lines NOT separated "
            "(text-based; see caveats). Cross-check with tokei/scc.\n")
    f.write(f"{'language':20} {'files':>7} {'total':>10} {'non-blank':>10}\n")
    tot_f = tot_l = tot_nb = 0
    for lang in sorted(lang_total, key=lambda k: -lang_total[k]):
        f.write(f"{lang:20} {lang_files[lang]:>7} {lang_total[lang]:>10} {lang_nonblank[lang]:>10}\n")
        tot_f += lang_files[lang]; tot_l += lang_total[lang]; tot_nb += lang_nonblank[lang]
    f.write(f"{'TOTAL':20} {tot_f:>7} {tot_l:>10} {tot_nb:>10}\n")

w("21_test_files.txt", [
    f"test files (heuristic): {len(test_files)}",
    f"  python test files: {len(py_test_files)}",
    f"  js/ts test files: {len(js_test_files)}",
    "",
    *sorted(test_files),
])
w("22_test_functions.txt", [
    f"python test functions (regex 'def test*('): {py_test_funcs}",
    f"js/ts test cases (regex 'it(|test('): {js_cases}",
])
w("23_assertions.txt", [
    "Text-based assertion counts. LIMITATION: regex over source; counts commented/"
    "string-literal 'assert' occurrences and cannot see runtime assertion density.",
    f"python 'assert' in test files: {assert_stmts}",
    f"python 'assert' across all .py (kept): {assert_all_py}",
    f"assert-like calls (pytest.raises/self.assert*/expect() in kept .py): {assert_like}",
])
with (RAW / "34_prometheus.txt").open("w", encoding="utf-8") as f:
    f.write(f"prometheus-related files (kept): {len(prom_files)}\n")
    f.write(f"{'match':8} {'class':32} path\n")
    for rp, how, klass in sorted(prom_files):
        f.write(f"{how:8} {klass:32} {rp}\n")
with (RAW / "37_largest_dirs_by_count.txt").open("w", encoding="utf-8") as f:
    for d, c in largest_dirs_count:
        f.write(f"{c:>7}  {d}\n")
with (RAW / "38_largest_dirs_by_bytes.txt").open("w", encoding="utf-8") as f:
    for d, b in largest_dirs_bytes:
        f.write(f"{b:>14}  {d}\n")
with (RAW / "39_largest_files.txt").open("w", encoding="utf-8") as f:
    for rp, sz, _ in largest_files:
        f.write(f"{sz:>14}  {rp}\n")
w("35_generated_vendored.txt", [
    "Generated / cached / dependency dirs found among non-.git files "
    "(matched against exclusion set):",
    *[f"  {seg}: {c} files, {excl_bytes_by_seg[seg]} bytes"
      for seg, c in sorted(excl_by_seg.items(), key=lambda kv: -kv[1])],
    "",
    "Repo-specific vendored/reference/evidence (kept, reported separately):",
    f"  vendored/reference: {cat_count.get('vendored/reference', 0)} files",
    f"  evidence: {cat_count.get('evidence', 0)} files",
    f"  reports: {cat_count.get('reports', 0)} files",
    f"  dependency lockfiles: {cat_count.get('dependency', 0)} files",
])

metrics = {
    "root": str(ROOT),
    "physical_all_files": all_count,
    "physical_all_bytes": all_bytes,
    "git_dir_files": git_count,
    "git_dir_bytes": git_bytes,
    "nongit_files": len(records),
    "excluded_files": len(excluded_nongit),
    "kept_files": len(kept),
    "kept_bytes": sum(sz for _, sz, _ in kept),
    "nongit_bytes": sum(sz for _, sz, _ in records),
    "by_category_files": dict(sorted(cat_count.items(), key=lambda kv: -kv[1])),
    "by_category_bytes": {k: cat_bytes[k] for k in cat_count},
    "ext_buckets": {**dict(bucket_count), "no_extension": noext,
                    "dockerfiles": dockerfiles, "helm_files": helm_files,
                    "k8s_like_yaml": k8s_like},
    "lines_by_language_total": dict(sorted(lang_total.items(), key=lambda kv: -kv[1])),
    "lines_by_language_nonblank": dict(lang_nonblank),
    "lines_total": sum(lang_total.values()),
    "lines_nonblank_total": sum(lang_nonblank.values()),
    "test_files": len(test_files),
    "py_test_files": len(py_test_files),
    "py_test_functions": py_test_funcs,
    "js_test_files": len(js_test_files),
    "js_test_cases": js_cases,
    "assert_in_tests": assert_stmts,
    "assert_all_py": assert_all_py,
    "prometheus_files": len(prom_files),
    "top_dirs_by_count": largest_dirs_count[:20],
    "top_dirs_by_bytes": largest_dirs_bytes[:20],
    "largest_files": [[rp, sz] for rp, sz, _ in largest_files[:20]],
    "excluded_by_segment": dict(sorted(excl_by_seg.items(), key=lambda kv: -kv[1])),
}
(ROOT / RECEIPT_NAME / "fs_metrics.json").write_text(
    json.dumps(metrics, indent=2), encoding="utf-8")

print(f"physical(all incl .git)={all_count}  nongit={len(records)}  kept={len(kept)}")
print(f"kept bytes={metrics['kept_bytes']}  lines_total={metrics['lines_total']}")
print(f"test_files={len(test_files)} py_test_funcs={py_test_funcs} prometheus={len(prom_files)}")
print("fs_metrics.json + raw/*.txt written")
