apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Cryptographic Agility Service
  namespace: default
  labels:
    app: Cryptographic Agility Service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Cryptographic Agility Service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
