apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Dark-Fiber Relay
  namespace: default
  labels:
    app: Dark-Fiber Relay
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Dark-Fiber Relay
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
