apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: Confidence Calibration Service
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: Confidence Calibration Service
