apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Contradiction Detection Service
  namespace: default
  labels:
    app: Contradiction Detection Service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Contradiction Detection Service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
