apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Chaos engineering hooks
  namespace: default
  labels:
    app: Chaos engineering hooks
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Chaos engineering hooks
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
