apiVersion: v1
kind: Service
metadata:
  name: Chaos engineering hooks
  namespace: default
  labels:
    app: Chaos engineering hooks
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: Chaos engineering hooks
  sessionAffinity: None
