apiVersion: v1
kind: Service
metadata:
  name: SASE Signal Ingestion Service
  namespace: default
  labels:
    app: SASE Signal Ingestion Service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: SASE Signal Ingestion Service
  sessionAffinity: None
