"""Security module for Thirstys Waterfall - Advanced Security Features"""

from .dos_trap import (
    CompromiseDetector,
    CompromiseEvent,
    CompromiseType,
    DiskSanitizer,
    DOSTrapMode,
    HardwareKeyDestroyer,
    InterfaceDisabler,
    MemorySanitizer,
    ResponseAction,
    SanitizationMode,
    SecretWiper,
    ThreatLevel,
    create_dos_trap,
)
from .hardware_root_of_trust import (
    AttestationStatus,
    HardwareInterface,
    HardwareRootOfTrust,
    HardwareType,
    HSMInterface,
    SecureEnclaveInterface,
    TPMInterface,
)
from .mfa_auth import (
    AuthContext,
    AuthLevel,
    AuthMethod,
    BiometricProvider,
    BiometricType,
    CertificateProvider,
    FIDO2Provider,
    MFAAuthenticator,
    PasskeyProvider,
    TOTPProvider,
)
from .microvm_isolation import MicroVMInstance, MicroVMIsolationManager
from .privacy_risk_engine import PrivacyRiskEngine, RiskLevel

__all__ = [
    "AttestationStatus",
    "AuthContext",
    "AuthLevel",
    "AuthMethod",
    "BiometricProvider",
    "BiometricType",
    "CertificateProvider",
    "CompromiseDetector",
    "CompromiseEvent",
    "CompromiseType",
    "DOSTrapMode",
    "DiskSanitizer",
    "FIDO2Provider",
    "HSMInterface",
    "HardwareInterface",
    "HardwareKeyDestroyer",
    "HardwareRootOfTrust",
    "HardwareType",
    "InterfaceDisabler",
    "MFAAuthenticator",
    "MemorySanitizer",
    "MicroVMInstance",
    "MicroVMIsolationManager",
    "PasskeyProvider",
    "PrivacyRiskEngine",
    "ResponseAction",
    "RiskLevel",
    "SanitizationMode",
    "SecretWiper",
    "SecureEnclaveInterface",
    "TOTPProvider",
    "TPMInterface",
    "ThreatLevel",
    "create_dos_trap",
]
