apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: Auto-scaling & self-healing configs
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: Auto-scaling & self-healing configs
