apiVersion: v1
kind: Service
metadata:
  name: Auto-scaling & self-healing configs
  namespace: default
  labels:
    app: Auto-scaling & self-healing configs
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: Auto-scaling & self-healing configs
  sessionAffinity: None
