apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Auto-scaling & self-healing configs
  namespace: default
  labels:
    app: Auto-scaling & self-healing configs
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Auto-scaling & self-healing configs
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
